### ISSUE TITLE
Function to launch a learnr tutorial within an IDE frame

### ISSUE THREAD

**Issue by garrettgman** [rstudio-education/gradethis#1]
The function should take a tutorial ID (url?) and open the tutorial in the viewer pane.

## Context:

How can we transition students from learnr tutorials to the IDE?
How can we provide more sophisticated tutorials that require the use of the IDE?

I would like to enable students to launch a learnr tutorial within the IDE viewer pane. The tutorial would be hosted online elsewhere, for example at shinyapps.io, and the student would access it through an iframe. This removes the need to provide the raw .Rmd to the student (which would contain the solutions).

Together with #2, this would create a complete assignment workflow.

**Comment by gadenbuie** [comment]
@garrettgman I'm closing this issue because I think this feature request is out of scope for gradethis. Please reopen if I've misunderstood.
