### ISSUE TITLE
gradethis is not available on CRAN

### ISSUE THREAD

**Issue by martscht** [rstudio-education/gradethis#103]
The package is not available on CRAN for R 3.6.3 making it very difficult for students to run learnr with its auto-check for dependencies (because the installation attempt fails).

**Comment by sclewis23** [comment]
Can you fix this?

**Comment by garrettgman** [comment]
@martscht your students should be able to install gradethis with the remotes package, i.e.

```r
remotes::install_github("rstudio-education/gradethis")
```

**Comment by sclewis23** [comment]
Is there a plan to have this on CRAN ?

**Comment by garrettgman** [comment]
Yes, but not a timeline.

**Comment by ajcullum** [comment]
Would it be possible to update the README.md to point users to the remotes package and gradethis install path as the default? It currently points users to CRAN for released versions. 

Thanks for the package - excited to try it out!

**Comment by gadenbuie** [comment]
We'll open a release issue when we're ready to release to CRAN
