### ISSUE TITLE
Handling created df

### ISSUE THREAD

**Issue by deepanshu88** [rstudio-education/gradethis#108]
If a student creates a new dataframe, how to check his result? For example : the code below checks result of - Species column having values cetosa and versicolor.

```
library(dplyr)
newdf <- filter(iris, Species %in% c("setosa", "versicolor"))

```
```
grade_result(
  pass_if(~ identical(.result, dplyr::filter(iris, Species %in% c("setosa", "versicolor"))),
          "Correct. Thumbs up!")
)

```

**Comment by schloerke** [comment]
Looks good to me

**Comment by deepanshu88** [comment]
Thanks. Getting this message - "Last value being used to check answer is invisible. See `?invisible` for more information". Can we ignore this one?

**Comment by chendaniely** [comment]
@deepanshu88 yes. you should be able to ignore the invisible warning. See this issue from `learnr`: https://github.com/rstudio/learnr/issues/369

**Comment by deepanshu88** [comment]
Using this option. It is giving error - unused argument warn_invisible = FALSE
`tutorial_options(exercise.checker = gradethis::grade_learnr, exercise.warn_invisible = FALSE)
`

**Comment by gadenbuie** [comment]
These kind of pass/fail checks should be much easier now with `grade_this()`
