### ISSUE TITLE
Add `on_error` option to grade_result / grade_test

### ISSUE THREAD

**Issue by schloerke** [rstudio-education/gradethis#109]
Related: https://github.com/rstudio/learnr/issues/356

If the user value supplied to grade_result is a `error_condition`, run the `on_error` method handling this.  

The default value for `on_error` should be `on_error = getOption("gradethis.grade_result.on_error", NULL)` (name can change) so that it can be set globally and overwritten locally.

By default, we were thinking of having `grade_code` be the default behavior if an error object is found.  This would only work if the proper `grade_code` fields are available.

This allows for `stop("boom")` to actually be valid code.

**Comment by schloerke** [comment]
Needs https://github.com/rstudio/learnr/issues/356 to be merged before being able to work

**Comment by gadenbuie** [comment]
`gradethis_setup()` sets `exercise.error.check.code = "grade_this_code()"` which resolves this issue
