### ISSUE TITLE
Assign Marks for Correct Answer

### ISSUE THREAD

**Issue by deepanshu88** [rstudio-education/gradethis#110]
Can we assign Marks for Correct Answer? For example student has answered 6 questions correct out of 10.  We need to see his result after exercise.

**Comment by chendaniely** [comment]
Related to #2, if you are using `learnr` you can implement your own logging here: https://rstudio.github.io/learnr/publishing.html#recording_events

**Comment by gadenbuie** [comment]
While gradethis handles auto-grading code answers, learnr is likely the better repo for this type of request.
