### ISSUE TITLE
Extending .result notation

### ISSUE THREAD

**Issue by dtkaplan** [rstudio-education/gradethis#113]
You evaluate conditions in an environment (see line 60 of `evaluate_condition.R`) that has a pre-defined object `.result`. This is very convenient. Could we add a few more components to this environment?  Say:

- `.code` - the user code as a character string
- `.env` - the environment *after* the code has been executed

**Comment by chendaniely** [comment]
This might be related to #86

**Comment by mattblackwell** [comment]
I just wanted to chime in and say this would be super useful since it would allow us to, for example, check if an object exists in the submitted environment as in `pass_if(~ exists(obj, evnvir = .env))`. It seems especially important since the current setup is so focused on the last expression. I have a use case where I want to check that they assigned a particular value to a particular name and then print that name, which is hard to do (unless I'm missing something).

**Comment by schloerke** [comment]
I can understand adding `.code`.

I believe it's a bug that the formula is not evaluated in the expected `.env`. I believe using `.env` is a little clunky.  Updating your example, it would (eventually) be something like `pass_if(~ exists(obj))`

**Comment by mattblackwell** [comment]
Yeah, `pass_if(~ exists(obj))` and similar approaches would be great and obviate at least my need for `.env`. Thanks!

**Comment by garrettgman** [comment]
I too would like to be able to access the students code as a character string in the `grade_results()` checks. This would help me write feedback that targets _how_ the student got the result. For example,

```r
grade_result(
    pass_if(
        ~result == 4 & str_detect(.code, "%>%"),
        "Good job, and you even used the pipe operator!"
    )
)
```

**Comment by gadenbuie** [comment]
This is now possible using `grade_this()`

```r
grade_this({
  if (identical(.result, 4)) {
    if (str_detect(.user_code, "%>%")) {
      pass("Good job, and you even used the pipe operator!")
    }
    pass("That works")
  }
  fail()
})
```

> ...this would be super useful since it would allow us to, for example, check if an object exists in the submitted environment as in `pass_if(~ exists(obj, evnvir = .env))`


We'll be working toward better documenting the magic environment variables that are available inside `grade_this()`. Checking that a user created an object is now possible using `.envir_result` in `grade_this()`.

```r
# user submission
x <- 1
y <- 3
```

```r
grade_this({
  if (!exists("x", .envir_result)) fail("Assign to `x`")
  if (!exists("y", .envir_result)) fail("Assign to `y`")
  if (identical(x + y, 4) pass("Good job!")
  fail("Try again")
})
```
