### ISSUE TITLE
What are the plans for gradethis over the next few months?

### ISSUE THREAD

**Issue by davidkane9** [rstudio-education/gradethis#116]
Is there a location at which tentative plans/timelines for gradethis are revealed/discussed?

I (and others, I suspect) are very interested in incorporating gradethis into our course workflows for September. But that, of course, depends on where gradethis will be at. I get very nervous when I see a package removed from CRAN . . .

**Comment by garrettgman** [comment]
There is no timeline for development; I and a few others are contributing to `gradethis` as we can. I think we will be able to address a few of the reported issues in `gradethis` over the summer, but I don't anticipate any major changes before fall semester.

`gradethis` has never been on CRAN, and wasn't removed. You can install `gradethis` with

```r
remotes::install_github("rstudio/gradethis")
```
