### ISSUE TITLE
gradethis unavailable for R version 4.0

### ISSUE THREAD

**Issue by mkfreeman** [rstudio-education/gradethis#117]
It appears as if `gradethis` is not available for the most recent version of R -- is there a plan to update this (and, relatedly, will it work on RStudio Cloud)? Thanks!
<img width="924" alt="gradethis_unavailable" src="https://user-images.githubusercontent.com/1373882/83355270-5f3dde00-a32c-11ea-9330-599b30a129c4.png">

**Comment by mkfreeman** [comment]
Perhaps relatedly, I'm unable to install from GitHub (though this may be an issue on my end?). 
<img width="1366" alt="github_install_error" src="https://user-images.githubusercontent.com/1373882/83355342-ef7c2300-a32c-11ea-8b8c-7db05c95ce01.png">

**Comment by muschellij2** [comment]
You need to edit ~/.Rprofile - add a final line (\n).  Also see
https://github.com/r-lib/remotes/#environment-variables:
> Setting R_REMOTES_NO_ERRORS_FROM_WARNINGS="true" avoids stopping the
installation for warning messages. Warnings usually mean installation
errors, so by default remotes stops for a warning. However, sometimes other
warnings might happen, that could be ignored by setting this environment
variable.

Best,
John

**Comment by chendaniely** [comment]
`gradethis` is not available on CRAN yet, that's why you're getting the error message when trying to use `install.packages`. See #103
