### ISSUE TITLE
Third Party integration?

### ISSUE THREAD

**Issue by lewkrr** [rstudio-education/gradethis#122]
@garrettgman tells me that this is the successor to <s>the</s> a `gradeR` package.  I am curious to know if there are plans to include integration with third party services such as GradeScope.  I ask because another, <s>the</s> a completely different `gradeR` package includes a `calcGradesWithGradescope()` function.

**Comment by garrettgman** [comment]
To clarify, this is the successor to a `gradeR` package that had to change its name because _that_ `gradeR` package was published to CRAN 😉.

**Comment by lewkrr** [comment]
Oh _that_ pesky `gradeR`  🙄  I've updated my previous comment to reflect that.  Cheers!
