### ISSUE TITLE
ggplot code copy and pasted from clipboard hint returns syntax error

### ISSUE THREAD

**Issue by slinnpsu** [rstudio-education/gradethis#135]
I'm having students edit ggplot code. If you edit to match the solution provided with the hint button, a correct answer is included, but if you copy from the clipboard a syntax error is returned unless the entire ggplot code is entered on one line.
The solution is:

ggplot(data=Counties, mapping=aes(x=factor(racial_majority))) +
  geom_bar() +
  labs(title = "Number of US Counties by Racial Majority",
       subtitle = "2016",
       x=NULL,
       y="Frequency",
       caption = "Source: Linn, Nagler, Zilinsky") +
  scale_x_discrete(na.translate = FALSE, labels = c("Black Majority" = "Black", "Hispanic Majority" = "Hispanic", "Other Majority" = "Other", "White Majority"= "White"))

 The error message is:

Uh oh, the R code produced a syntax error: <text>:1:64: unexpected input 1: ggplot(data=Counties, mapping=aes(x=factor(racial_majority))) + ^

The error disappears if all code is on one line or if the following code is given to edit and students replace the XXXXs

ggplot(data=Counties, mapping=XXXX(XXX=factor(racial_majority))) +
  XXXX() +
  labs(title = "Number of US Counties by Racial Majority",
       subtitle = "2016",
       x=NULL,
       y="XXXX",
       caption = "Source: Linn, Nagler, Zilinsky") +
  scale_x_discrete(na.translate = FALSE, labels = c(XXXX))

**Comment by gadenbuie** [comment]
This is most likely platform-specific and an issue better handled in [learnr](https://github.com/rstudio/learnr/issues).
