### ISSUE TITLE
Differentiate between "strings" and objects in messages

### ISSUE THREAD

**Issue by garrettgman** [rstudio-education/gradethis#138]
solution: `library("dplyr")`
student: `library(dplyr)`
message: "In library(dplyr), I expected dplyr where you wrote dplyr. Try it again. Perseverence is the key to success."

We should make this more clear. The teacher expected `"dplyr"`.

**Comment by VincentGuyader** [comment]
today 

`gradethis:::prep("dplyr") == gradethis:::prep(as.name("dplyr"))` is `TRUE`

We have to be sure that every quoted character passed to `prep` return an explicit quoted character . like this :


``` r
gradethis:::prep("dplyr")
#> [1] "\"dplyr\""
gradethis:::prep(as.name("dplyr"))
#> [1] "dplyr"
```

To do this we need to correct `prep` from  : 

```
function(text) {
  # NOTE: `[` does not work well for assign `<-` and would
  # grab whole expression ending up with: NULL <- NULL.
  # this extra condition to use `[[` works, but requires further 
  # investigation for a cleaner solution.
  if (is_infix(text)) {
    text <- text[[1]]
  } else if (is.call(text)) {
    text <- text[1]
  } 
  if (!is.character(text)) text <- 
      deparse_to_string(text)
  text
}
```
to 

```
function(text) {
  # NOTE: `[` does not work well for assign `<-` and would
  # grab whole expression ending up with: NULL <- NULL.
  # this extra condition to use `[[` works, but requires further 
  # investigation for a cleaner solution.
  if (is_infix(text)) {
    text <- text[[1]]
  } else if (is.call(text)) {
    text <- text[1]
  } 
        deparse_to_string(text)
}
```
`deparse_to_string` need to be always used.

this implies a lot of unit testing modification. I try to do this
