### ISSUE TITLE
Allow author to create objects to use in pass and fail checks

### ISSUE THREAD

**Issue by garrettgman** [rstudio-education/gradethis#150]
I'd like to be able to safely create objects in `grade_result()` to use in my `pass_if()` and `fail_if()` checks. Here is an example, the fictitious `setup` argument takes a chunk of code that will be run in the same environment that the `fail_if()` checks will be run in. The `setup` code is run before these checks, so the checks can rely on its output, greatly magnifying the number of things I can check. I assume that the parent of this environment is the student's environment after the student code has run. I also assume that `.result` is available to code run in this environment. 

```r
grade_result(
   setup = {
     .solution <- iris %>% filter(Species == "Setosa")
     .common_error <- iris %>% filter(Species == "Virginica")
     .max <- .result %>% pluck("Sepal.Length) %>% max()
   },
   fail_if(~nrow(.result) != nrow(.solution), "custom message 1"),
   fail_if(~ncol(.result) != ncol(.solution), "custom message 2"),
   fail_if(~names(.result) != names(.solution), "custom message 3"),
   fail_if(~identical(.result, .common_error), "You filtered the wrong group"),
   fail_if(~.max == 1.3, "custom message 4"),
)
```

**Comment by VincentGuyader** [comment]
I will try this one as a warmup :)

**Comment by gadenbuie** [comment]
Use `grade_this()`
