### ISSUE TITLE
Provide way to check that student has run pre-filled, correct code

### ISSUE THREAD

**Issue by garrettgman** [rstudio-education/gradethis#151]
I want to provide the student essential code to run, and then double check that he or she has run it. For example,

````markdown
Run the code below to load the packages that we will use.

```{r load, exercise = TRUE}
library(tidyverse)
library(readxl)
```
````

The key here is that:
1. The code is already complete
2. The code is already correct

I just need to check that the student ran it. IIUC, I cannot use `grade_result()` to do this because `grade_result()` automatically runs the code in the student chunk to supply `.result`. In other words, `grade_result()` does not reveal whether or not the student ran the code, `grade_result()` assumes that they have run the code and then focuses on whether the code produced the right result.

**Comment by schloerke** [comment]
To get half way there, there could be a new function to wrap:

```
grade_result(
	pass_if(~TRUE),
    correct = "Thanks for running the code!"
)

**Comment by VincentGuyader** [comment]
I'm not sure to understand : 

is it not possible to use `grade_code` here ?

````markdown



```{r load, exercise = TRUE}
library(tidyverse)
library(readxl)
```

```{r load-solution}
library(tidyverse)
library(readxl)
```


```{r load-check}
grade_code("Thanks for running the code!")
```
````

the student have to pass exactly the same content

**Comment by gadenbuie** [comment]
I think this resolved, or can be handled as suggested in https://github.com/rstudio-education/gradethis/issues/151#issuecomment-723961166
