### ISSUE TITLE
issue with `grade_learnr` unit test

### ISSUE THREAD

**Issue by VincentGuyader** [rstudio-education/gradethis#158]
we have an error on check here : 

>-- 1. Failure: Grade learnr check_code (@test_grade_learnr.R#98)  --------------
grade_learnr(user_code = "function(") not equal to grade_feedback(graded(correct = FALSE, message = "The user code of 'function(' produced an parsing error: <text>:2:0: unexpected end of input\n1: function(\n   ^")).
Component "message": 1 string mismatch

> == testthat results  ===========================================================
[ OK: 486 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
>1. Failure: Grade learnr check_code (@test_grade_learnr.R#98) 

this is the failing test : 

```
  expect_equal(
    grade_learnr(user_code = "function("),
    grade_feedback(
      graded(
        correct = FALSE,
        message = "The user code of 'function(' produced an parsing error: <text>:2:0: unexpected end of input\n1: function(\n   ^"
      )
    )
  )
```

**Comment by garrettgman** [comment]
This must have been passing before. Do we know which change broke it? It is alright to rewrite the test if that is the right course of action (particularly likely with this package!). 

Is it safe to say that fixing the test should be part of the PR that breaks it?
