### ISSUE TITLE
Enable markdown in gradethis feedback

### ISSUE THREAD

**Issue by gadenbuie** [rstudio-education/gradethis#176]
Allowing gradethis errors to include HTML or markdown would greatly enhance user feedback. Here, roughly, is what would be required to enable this.

- [ ] Keep `glue_with_env()` from trying to glue HTML tags
- [ ] `graded()` should expect non-NULL `message` rather than enforce single character
- [ ] `htmltools::HTML()` should make it through `glue_with_env()` and retain `"html"` class
- [ ] `graded()` should process character `message` with `commonmark::markdown_html()`
    - Should this happen for all feedback messages? Alternatively, authors could signal markdown intent by using a `md()` helper function.
- [ ] `graded()` pass through HTML strings and tags
- [ ] Confirm that gradethis results are handled as expected in `learnr:::question_messages()`
- [ ] Add and update tests

**Comment by schloerke** [comment]
I'd be up for `learnr` upgrading all text like feedback messages to HTML if flagged with `md()`.
