### ISSUE TITLE
Checking error when function parameters in student code out of order

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/gradethis#177]
`> sessioninfo::session_info()`

```
VP gradethis   * 0.1.0.9004  2020-12-07 [?] Github (rstudio-education/gradethis@891564c)
 P  learnr      * 0.10.1.9006 2020-12-07 [?] Github (rstudio/learnr@7eb2b29)             
```

Exercise with checks:

    ```{r showwithtax-code-0, exercise = TRUE}
    ____ <- function(____, ____) {
      print(amount * (1 + taxRate))
    }
    showWithTax(100, 0.07)
    ```

    ```{r showwithtax-code-0-solution}
    showWithTax <- function(amount, taxRate) {
      print(amount * (1 + taxRate))
    }
    showWithTax(100, 0.07)
    ```

    ```{r showwithtax-code-0-check}
    grade_code(
      correct = "Opah!",
      incorrect = "Do you have the parameters in the right order?"
    )
    ```

Submit correct answer, get the response `Assertion on 'solution_code' failed: Must have length 1, but has length 4.` (Get the same response submitting an incorrect answer in which the function parameters are declared in reverse order as `(taxRate, amount)`.)

**Comment by garrettgman** [comment]
FWIW, `grade_code()` has not been tested against the case where we ask the student to write a function. There may be some surprises.

In general, I recommend that we grade work with `grade_result()` and rely on `grade_code()` to append a code suggestion in the result that `grade_result()` determines that their code is wrong. It seems to make for a much smoother student experience.
