### ISSUE TITLE
`code_feedback()` should work with function definitions

### ISSUE THREAD

**Issue by schloerke** [rstudio-education/gradethis#179]
https://github.com/rstudio-education/gradethis/issues/177#issuecomment-740143000
> FWIW, grade_code() has not been tested against the case where we ask the student to write a function. There may be some surprises.
> 
> In general, I recommend that we grade work with grade_result() and rely on grade_code() to append a code suggestion in the result that grade_result() determines that their code is wrong. It seems to make for a much smoother student experience.
> \- @garrettgman

Reprex from #178:

```r
code_feedback("function(x, y) x + y", "function(y, x) x + y")
#> In function(x, y) x + y, I did not expect your call to () to include y = . You may have included an unnecessary argument, or you may have left out or misspelled an important argument name.
```

And the many different forms of missing/extra/duplicated arguments

**Comment by gadenbuie** [comment]
I think that the changes I just added to #178 address almost all of this, at least in terms of missing arguments, extra arguments and differing default argument values. 

Duplicated arguments return a parse error. What feedback do you expect for this?

```r
code_feedback("function(x, y, y) x + y", "function(x, y) y + x")
#> Error in parse(text = text, keep.source = FALSE) : 
#>   repeated formal argument 'y' on line 1
```

**Comment by schloerke** [comment]
I am in the camp of things that can not be parsed should not be graded. There are too many odd behaviors to solve for now.

Similar: 
```r
code_feedback("function(x, y, ) x + y", "function(x, y) x + y")
Error in parse(text = text, keep.source = FALSE) :
  <text>:1:16: unexpected ')'
1: function(x, y, )
```
