### ISSUE TITLE
code_feedback() should handle multiline solution code

### ISSUE THREAD

**Issue by gadenbuie** [rstudio-education/gradethis#181]
Somehow a chunk like

````
```{r reprex-solution}
1
2
```
````

ends up in `code_feedback()` as a vector of strings, resulting in this sort of error message:

```r
code_feedback("1\n2", c("1", "2"))
#> Error in chkm8_single_character(x, null.ok = FALSE, name = name): Assertion on 'solution_code' failed: Must have length 1, but has length 2.

to_expr(c("1", "2"), name = "reprex")
#> Error in chkm8_single_character(x, null.ok = FALSE, name = name): Assertion on 'reprex' failed: Must have length 1, but has length 2.
```

**Comment by schloerke** [comment]
Is this a learnr problem sending a string vector? Or is this a gradethis problem?

**Comment by gadenbuie** [comment]
It's a little of both. It seems like learnr sends a string vector for `solution_code`, but gradethis used to handle the string vector.

From cfd8499 (the last commit before #163)

```
grade_code(
  grader_args = list(
    user_quo = as.expression(rlang::parse_exprs("1\n2")),
    solution_quo = as.expression(rlang::parse_exprs(c("1", "2")))
  )
)
#> $message
#> Lovely job!  
#> 
#> $correct
#> [1] TRUE
#> 
#> attr(,"class")
#> [1] "grader_graded"
```

Current version (92b09bf3), where `grade_this_code()` added an assertion on `solution_code` being length 1.

```r
code_feedback("1\n2", c("1", "2"))
#> Error in chkm8_single_character(x, null.ok = FALSE, name = name): Assertion on 'solution_code' failed: Must have length 1, but has length 2.

grade_code()(list2env(list(
  .user_code = "1\n2",
  .solution_code = c("1", '2')
)))
#> Error in chkm8_single_character(x, null.ok = FALSE, name = name): Assertion on 'solution_code' failed: Must have length 1, but has length 2.
```

Prior to #163, `grade_code()` did essentially the following to both `user` and `solution`

```
code <- rlang::as_quosure(parse(text = "1\n2"))
code <- rlang::get_expr(code)
detect_mistakes(code, code)
#> NULL
```

and because `detect_mistakes()` walks the expressions recursively it was okay that `solution` wasn't length 1.

```
detect_mistakes(code, parse(text = "1\n3"))
#> I expected 3 where you wrote 2.
```

So I think gradethis should accommodate the string vector.

If we want to address this in learnr, I think at least the `check` and `solution` chunks are passed as string vectors with a `chunk_opts` attribute as returned by `knitr::knit_code$get(label)` [here](https://github.com/rstudio/learnr/blob/7eb2b298699733a9a64d9c15a728b0ca6a4d68d5/R/knitr-hooks.R#L73).

**Comment by schloerke** [comment]
Correct. `gradethis::code_feedback()` should accommodate a string vector.

As long as `str2expression()` works with a vector, we can remove the length restriction inside [`to_expr`](https://github.com/rstudio-education/gradethis/blob/92b09bf3e6bdc3a8cd550be2245e272da3d6bae3/R/grade_this_code.R#L181)
