### ISSUE TITLE
Happy sounds

### ISSUE THREAD

**Issue by higgi13425** [rstudio-education/gradethis#186]
It would be nice to be able to add, in addition to random_praise(), a happy sound from the beepr package when students get a solution correct.

**Comment by gadenbuie** [comment]
With the latest version of gradethis you can actually do this (sort of)! You can't use the beepr package, but if you find or put a sound online, you can include the HTML required in your feedback message to have the sound play when the feedback is returned.

```r
grade_this({
  if (!identical(.result, 4)) fail("Nope, the answer is 4")
  pass('You did it! <audio src="http://www.thefunnysounds.com/espanol/a3/best/aplauso2.mp3" type="audio/mp3" autoplay="TRUE"></audio>')
})
```

**Comment by gadenbuie** [comment]
FYI this particular approach only works on some browsers, but something like this is certainly possible.
