### ISSUE TITLE
Should check chunks require checking code to be returned last?

### ISSUE THREAD

**Issue by schloerke** [rstudio-education/gradethis#19]
It is fine to be forced to be returned last, but it should be documented

**Comment by chendaniely** [comment]
since we're pulling out the checking code via `length(user_code)` is it worth trying to pass that value in as a parameter with a default value of `length(user_code)` just so there's an API to override the value?

or does that not make sense because the length of the check code will vary too much?

**Comment by schloerke** [comment]
That'd be hard to remember / figure out as the parsed lines of code wont match the actual lines of code.

**Comment by gadenbuie** [comment]
This is true
