### ISSUE TITLE
Bring pass_if() and fail_if() to grade_this()

### ISSUE THREAD

**Issue by gadenbuie** [rstudio-education/gradethis#197]
Using `pass_if()` and `fail_if()` inside `grade_this()` currently doesn't work. 

``` r
grade_this({
  pass_if(.result == 4 && grepl("\\d \\+ \\d", .user_code), "yes")
  fail_if(TRUE, "no")
})(list(
  .result = 4,
  .user_code = "1 + 3"
))
#> $x
#> [1] TRUE
#> 
#> $message
#> [1] "no"
#> 
#> $correct
#> [1] FALSE
#> 
#> $type
#> [1] "value"
#> 
#> attr(,"class")
#> [1] "gradethis_condition"
```

To the end user, this result in a message in the tutorial

```
A problem occurred with your teacher’s grading code. Defaulting to incorrect
```

and a warning in the console:

```
`___-check` chunk did not mark an answer as correct or incorrect.
Consider adding a `pass()` or `fail()` at the end of your `___-check` code
```

Given the prevalence of `pass_if()` and `fail_if()` in existing gradethis code, I think we should make these work for `grade_this()`. If not, at the very least we should have stronger checks with better advice when either are used inside `grade_this()`.

A sketch of what I think we would need to do

- Update the calling handlers in `capture_graded()` to handle a `gradethis_condition`
- That calling handler would turn the `gradethis_condition` into a `gradethis_graded` condition via `graded()`
- Update calls to `capture_graded()`?

**Comment by schloerke** [comment]
I disagree with adding these as I don't want the old implementation using formulas or functions to persist.

I'd rather have authors use `if (expr) pass(msg)`.  

-----------------

Or we can deprecate the existing implementation of `pass_if()` and rewrite them from scratch. I am all for chopping the old code.
