### ISSUE TITLE
Submit answers or log to instructor

### ISSUE THREAD

**Issue by garrettgman** [rstudio-education/gradethis#2]
I need a way for students to submit their work to the teacher.  Ideally, this would be integrated into a learnr button.

I'm not yet sure what exactly should be submitted. The log of the students work in the tutorial seems like a good candidate.

I'm not yet sure where the submission should go. One idea is that the submission function/button would place an entry in the master log that a teacher could then work with using grader tools.

**Comment by LucyMcGowan** [comment]
@garrettgman: Is there a way to access these logs you mention here? I am investigating incorporating {learnr} + {gradethis} for a study protocol.

**Comment by chendaniely** [comment]
Capturing the results may be a `learnr` task. But I did think about having the `graded` object also include the instructor solution and the student solution. It'll make `gradethis` a little more self-contained and portable outside of `learnr` so other extensions can be written for it?

**Comment by schloerke** [comment]
. @chendaniely is correct, it is currently a `learnr` responsibility and is already implemented.  

Unfortunately there is not any "save logs to a sql database" currently implemented.  Please see https://rstudio.github.io/learnr/publishing.html#recording_events to implement your own logging.

**Comment by LucyMcGowan** [comment]
Awesome, thank you both!

**Comment by gadenbuie** [comment]
I believe this request is covered by features in learnr
