### ISSUE TITLE
Update gradethis_setup() signature (breaking change)

### ISSUE THREAD

**Issue by gadenbuie** [rstudio-education/gradethis#212]
I'm still a bit unsatisfied with the current state of `gradethis_setup()`. Especially now that it isn't strictly required, it bugs me that the first arguments are all setting learnr options instead of gradethis options.

Instead of

```r
gradethis_setup <- function(
  exercise.timelimit = NULL,
  exercise.checker = NULL,
  exercise.error.check.code = NULL,
  ...,
  pass = NULL,
  fail = NULL,
  code_correct = NULL,
  code_incorrect = NULL,
  fail_code_feedback = NULL,
  pipe_warning = NULL,
  allow_partial_matching = NULL
) {
 #...
}
```

I'd like to propose

```r
gradethis_setup <- function(
  pass = NULL,
  fail = NULL,
  ...,
  code_correct = NULL,
  code_incorrect = NULL,
  fail_code_feedback = NULL,
  pipe_warning = NULL,
  allow_partial_matching = NULL,
  exercise.checker = gradethis_exercise_checker,
  exercise.timelimit = NULL,
  exercise.error.check.code = NULL
) {
 #...
}
```

With this new signature, `pass` and `fail` come first as they're the most likely to be customized. `...` are still passed to `learnr::tutorial_options()` but also serve to require full argument names. gradethis options come next, followed by learnr options. I've also added the default values of the `exercise.checker` option, since this value will always be set by `gradethis_setup()` unless given another value.

It's hard to judge the impact of this change, but I haven't found any publicly available examples of `gradethis_setup()` using custom values, so I doubt the impact will be large.

**Comment by gadenbuie** [comment]
cc @schloerke and @garrettgman what do you think?

**Comment by schloerke** [comment]
👍 (just mark as breaking change in news)
