### ISSUE TITLE
Should we remove maybe_code_feedback()?

### ISSUE THREAD

**Issue by gadenbuie** [rstudio-education/gradethis#217]
Currently we can use `maybe_code_feedback()` in the default `fail()` message, which can be turned on or off via the `fail_code_feedback()` argument of `grade_this()` or the `gradethis.fail_code_feedback` option.

I don't like that this argument only has an effect on the output **if and only if** `maybe_code_feedback()` was used for the default message.

The motivation for it to exist is that it's otherwise difficult to adjust the default values of the `fail()` message. This makes sense, but maybe we should take a different approach:

1. Use the `...` and `with_options()` to let users temporarily set options for the current exercise check
2. Get rid of `maybe_code_feedback()` and `fail_code_feedback` and have the user adjust the default fail message.

This leads to (maybe) a bit more typing but gives the user more control. It's been hard to explain the many ways that `fail()`, `code_feedback()`, `maybe_code_feedback()`, `gradethis.fail` and `gradethis.fail_code_feedback` and to ensure they appear in the documentation in a discoverable and understandable way.

**Comment by garrettgman** [comment]
TBH, so far when I've used `maybe_code_feedback()`, I've wanted to set it at the `grade_check()` as in "if the student code trips any of the `fail()`s below add `code_feedback()` to the end of message returned by whichever `fail()` is tripped.

In other words, I haven't thought of a case where I want to add `code_feedback()` for one failure mode only, although those cases could be out there.

**Comment by gadenbuie** [comment]
Quick note, mostly for myself. We can't remove `maybe_code_feedback()` because it serves a slightly different purpose from `code_feedback()`. 

The biggest API hurdle for `code_feedback()` is that it returns a string with feedback or `NULL` if there aren't any. This means that it's not safe for use it in _any_ arbitrary glue string because `NULL` values in glue causes the entire string to be empty.

We could change the `code_feedback()` API or we could advise authors to use `"{code_feedback() %||% ''}"`, but I think the `code_feedback()` contract has been around for a while and the second seems to unwieldy.

`maybe_code_feedback()` is designed for use in the glue strings and has additional features — like adding space before and after, ensuring the output is always a character, and default argument values controlled by global options for high level control. We might want to adjust those options/arguments but I think the function serves a need.

For the issue of adding code feedback to all incorrect messages, I think we'll need a different solution and I have in mind a function `with_code_feedback()` that would capture all `fail()` grades and add the code feedback. (And this would require renaming the current internal `with_code_feedback()`.)
