### ISSUE TITLE
check_code should not require use of `standardise_call`

### ISSUE THREAD

**Issue by schloerke** [rstudio-education/gradethis#26]
It's confusing and hard to test.  There should never be a "it's voodoo" when explaining how it works.

Current:
```r
check_result(args, grader_args, learnr_args) # checks result
```

Proposed:
```r
ck_fn <- check_result(args) # returns function that accepts grader_args / learnr_args
ck_fn # will be called after "*-check" evaluation as `ck_fn(grader_args, learnr_args)`
```

This allows for any function to be produced in any way as long as a function is returned from the chunk that accepts `grader_args` and `learnr_args`.  We do not need to be cautious of parameter expansion as `grader_args` is already included and is a list.

This would require functions like `check_result` to return a function that does the evaluation.  Rough example:

```r
new_check_result(...) {
  results <- list(...)

  function(grader_args, learnr_args) {
    # check results here

    graded(TRUE)
  }
}
```

This would clean up the logic inside grade_learnr and would be much easier to enforce / document

**Comment by gadenbuie** [comment]
Implemented with `grade_this()`
