### ISSUE TITLE
Might need envir_prep in evaluate_condi

### ISSUE THREAD

**Issue by chendaniely** [rstudio-education/gradethis#27]
might need envir_prep. idk for sure. Not the priority right now

_Originally posted by @schloerke in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTgzNDcyMDcyOnYy/pull_request_review_threads/discussion_

not sure if this is needed since the function is called within check_result. but can come back to it if the instructor puts in a function that makes calls to variables in the environment.

**Comment by gadenbuie** [comment]
`evaluate_condi` was deprecated
