### ISSUE TITLE
Remove `~` from the pipe message sent to student

### ISSUE THREAD

**Issue by garrettgman** [rstudio-education/gradethis#33]
From #17, the first code returns

> > I see that you are using pipe operators (e.g. %>%), so I want to let you know that this is how I am interpretting your code before I check it: ~gather(who, key, value, new_sp_m014:newrel_f65, na.rm = FALSE) I expected na.rm = TRUE where you wrote na.rm = FALSE. Try it again. I have a good feeling about this.

We should remove the `~` that appears in the message as it will confuse students. In this case , the `~` appears before `gather`.

Discussion for this comment: https://github.com/rstudio-education/grader/issues/30#issuecomment-509682993

**Comment by chendaniely** [comment]
Weird that the `\n` in https://github.com/rstudio-education/grader/blob/fb75ed249ba621892b6ff91f2e0e94d7a2ab1d7f/R/check_code.R#L95 are not being displayed...

**Comment by chendaniely** [comment]
also, don't know where the `~` is coming from... I can't seem to replicate the `~` that is returned in the message

```r
> ca <- grader:::unpipe_all(quote(head(who, 2) %>% gather(key, value, new_sp_m014:newrel_f65, na.rm = FALSE)))
> ca
gather(head(who, 2), key, value, new_sp_m014:newrel_f65, na.rm = FALSE)
> deparse(ca)
[1] "gather(head(who, 2), key, value, new_sp_m014:newrel_f65, na.rm = FALSE)"
```

**Comment by gadenbuie** [comment]
Fixed
