### ISSUE TITLE
strict_check does not correctly unpipe solutions with multiple pipes

### ISSUE THREAD

**Issue by garrettgman** [rstudio-education/gradethis#4]
From the Nested Data section of https://tutorials.shinyapps.io/list-columns:
<img width="1731" alt="screen shot 2018-06-13 at 11 36 33 am" src="https://user-images.githubusercontent.com/85014/41365124-2f9891cc-6efe-11e8-949d-d8ab57527d70.png">

**Comment by garrettgman** [comment]
A problem is that the default response assumes that the user's code appears in an unpiped order, e.g.

```
strict_check(success = "Nice Job!", 
             solution = quote(mean(pluck(iris, "Sepal.Length"))), 
             user =     quote(pluck(iris, "Sepal.Length")))
# I expected mean where you wrote pluck. Please try again.
```
The response is confusing if the user submitted a pipe

```
strict_check(success = "Nice Job!", 
  solution = quote(iris %>% pluck("Sepal.Length") %>% mean()), 
  user =     quote(iris %>% pluck("Sepal.Length")))
# I expected mean where you wrote pluck. Please try again.
```

**Comment by garrettgman** [comment]
This extends to all infix operators

```r
strict_check("nice!", solution = quote(1 + 2 + 3), user = quote(1 + 2))
# I expected + where you wrote 1. Please try again.
```

**Comment by gadenbuie** [comment]
I think this issue is now covered by more specific issues.
