### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by chendaniely** [rstudio-education/gradethis#42]
Stale branches, @garrettgman can these be deleted?

- [x] `attempt-1.0`

Updated last year by garrettgman

- [ ] `infix-checking-bug`

Updated last year by garrettgman

- [x] `pseudo-pipe-approach`

Updated last year by garrettgman

- [x] `outside-in`

Updated last year by garrettgman

**Comment by schloerke** [comment]
`infix-checking-bug` is the only branch that hasn't already been merged.

**Comment by chendaniely** [comment]
I deleted all the other branches except for `infix-checking-bug`
