### ISSUE TITLE
3 parts to a message

### ISSUE THREAD

**Issue by chendaniely** [rstudio-education/gradethis#44]
praise/encouragement + question specific + correct/incorrect message

e.g.,

```
             question specific (e.g., from pass_if)
             v
"You did it! That's the correct answer. Next, we'll see how we can apply this to dataframes."
^                                       ^
praise/encouragement                    correct message
```

There's currently only 2.  The "praise/encouragement" is overwritten by "correct".

**Comment by schloerke** [comment]
This would work, right?

`correct = "{praise()} {message} Next, we'll see how we can apply this to dataframes."`

**Comment by chendaniely** [comment]
Is the glue notation something we want instructors to use? I initially thought of some boolean value to control whether or not `praise` gets shown. 

#40 shows that whatever gets passed into `correct` becomes the final message, and messages from `pass_if` are ignored.

**Comment by schloerke** [comment]
if `correct = "VALUE"` with no `"{message}"` component, then there will be no message part from the user.  So #40 examples do not respect the messages being returned from the condi objects.

If I remember right, Garrett and I were thinking of having `correct` and `incorrect` default to 

```r
correct = getOption("grader.correct", "{ praise() } { .message }",
incorrect = getOption("grader.incorrect", "{ .message } { encourage() }"
```

**Comment by chendaniely** [comment]
Changes to the `check_result` api will look like this for the instructor:

```r
check_result(
  pass_if(~ .result == 5, message = "You got it correct!"), # pass_if creates .message
  fail_if(~ .result == 42, message = "Not quite correct.")
  correct = "Next let's see what happens when we have missing NA values.",
  incorrect = "Remember the mean is created using the mean() function"
  )
)
```

If the message is correct it will create

```r
"Lovely job! You got it correct! Next let's see what happens when we have missing NA values."
```

If the message is incorrect it will create

```r
"Not quite correct. Remember the mean is created using the mean() function. Give it another try."
```
