### ISSUE TITLE
gradethis demo - error

### ISSUE THREAD

**Issue by mehtapd** [rstudio-education/gradethis#80]
`gradethis::gradethis_demo()` 
gives error...
"Error in f(...) : does not exist"

Run Document from within RStudio (grading-demo.Rmd) thriws an error 
"Error occured while checking the submission"

**Comment by jimmyrigby94** [comment]
I am getting both errors as well. 

I am not sure what the root of the gradethis_demo() error is, but it seems like there is a scoping problem with the grade_result() function used in the demo.

I get the same error within a separate learnr tutorial (Error occurred while checking the submission). The rmarkdown pane is producing another error `Can't extract an environment from a call`.

[Minimial Example.zip](https://github.com/rstudio-education/gradethis/files/3653649/Minimial.Example.zip)

**Comment by ianmcampbell** [comment]
I am getting both of these errors as well. Let me know if there's anything I can do to help with debugging. 

[SessionInfo.txt](https://github.com/rstudio-education/gradethis/files/3691465/SessionInfo.txt)

**Comment by jimmyrigby94** [comment]
@ianmcampbell  Here is a temporary fix external to gradethis. It is less than ideal but gets the job done. https://github.com/jimmyrigby94/jr_tools/blob/master/Automated%20Testing/Test%20Learnr.Rmd
