### ISSUE TITLE
Submit Answer Error: Can't extract an environment from a call

### ISSUE THREAD

**Issue by jimmyrigby94** [rstudio-education/gradethis#82]
Although the issue https://github.com/rstudio-education/gradethis/issues/80 is resolved, the error mentioned in https://github.com/rstudio-education/gradethis/issues/80#issuecomment-535102162 is still occurring across multiple work stations. 

After doing a bit of digging it seems that the error is stemming from the checker function. Specifically the following line. 

`grading_code <- rlang::call_standardise(parsed_check_code[[length(parsed_check_code)]], 
            envir_prep)`

envir_prep is `null` in the example, so evaluating the code within this environment doesn't make sense. I think this is likely an issue with the current control flow.

![image](https://user-images.githubusercontent.com/47652843/66581490-c57bb380-eb45-11e9-9b10-0d0bced8f9c5.png)

**Comment by gadenbuie** [comment]
I think this has been fixed as I can't reproduce this with the latest gradethis and learnr. @jimmyrigby94 If you're still seeing this issue, please feel free to re-open with additional details.

<details><summary>Reprex</summary>

````
---
title: "Tutorial"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)

knitr::opts_chunk$set(echo = FALSE)
```

## Topic 1

```{r grade_result, exercise=TRUE}
3
```

```{r grade_result-check}
grade_result(
  fail_if(~ .result<4, "Higher."),
  fail_if(~ .result>4, "Lower."),
  pass_if(~ identical(.result, 4), "Correct!")
)
```
````

</details>
