### ISSUE TITLE
Return the student and instructor solutions in the graded object

### ISSUE THREAD

**Issue by chendaniely** [rstudio-education/gradethis#86]
This is related to #2. But should `gradethis` return an object that contains the student solution and instructor solution?

It should help with `learnr` logging student answers, but it will also help make `gradethis` more self-contained and extensiable

**Comment by garrettgman** [comment]
I think it is simpler for gradethis to return the feedback message alone. This follows the tidyverse philosophy that each function should do one thing well—which I agree with. For us, gradethis functions require the student solution and the instructor solution as input, so whatever is calling gradethis already has them to pass to a logger, etc.

**Comment by chendaniely** [comment]
Does it matter that `gradethis` does its own code standardization and `unpipe`? because what users (student and instructor) pass into `gradethis` is not necessarily what is "used" to check.

**Comment by schloerke** [comment]
@chendaniely 

> Does it matter that gradethis does its own code standardization and unpipe?

No. I think if it more like a hashing hit / miss.  We could turn all code into piped code or de-pipe all code.  Piped and de-piped code is equivalent in execution, so both should be equivalent code.  Same applies to function parameters.

**Comment by gadenbuie** [comment]
We think that the `grade_this()` function has everything it needs to construct the feedback message
