### ISSUE TITLE
RStudio Connect error: "there is no package called 'gradethis'" when hint has extra quotes 

### ISSUE THREAD

**Issue by andreavargasmontero** [rstudio-education/gradethis#89]
When publishing a tutorial on Connect I noticed this error: 

<img width="1226" alt="Screen Shot 2020-02-25 at 12 11 42" src="https://user-images.githubusercontent.com/53089319/75287085-5eeaef80-57df-11ea-952b-6f73bf70b006.png">

After some digging I found that the issue was this hint:

```
#```{r separate-hint-1}

"into = c("participante", "sexo", "vocal"), sep = "-""

#```
```
And after some tries I understood that the way to fix it was doing this:
```
#```{r separate-hint-1, eval=FALSE, include=FALSE}

into = c("participante", "sexo", "vocal"), sep = "-"

#```
```
I thought that hints, by default, weren’t evaluated.

**Comment by schloerke** [comment]
The error provided states something about `gradethis` not being found.

I would make sure you have gradethis installed from github before deploying the tutorial.  If packrat finds a locally installed package, it will **not** upload the source and will fail like the error above.

```r
remotes::install_github("rstudio-education/gradethis")
```

**Comment by schloerke** [comment]
I still believe the hints are not evaluated.

Example file:

````md
---
title: "Hello, Tutorial!"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
```

Text

Text

Text

Text

Text

Text

Text

```{r addition-hint}
broken code, 4
```

```{r addition, exercise=TRUE}
1 + 1
```
````

Hint: 
<img width="1547" alt="Screen Shot 2020-02-26 at 2 08 45 PM" src="https://user-images.githubusercontent.com/93231/75378413-9f12a680-58a1-11ea-81a7-8188514cd3fd.png">

**Comment by andreavargasmontero** [comment]
Thanks for replying. I already tried de `remotes::install_github("rstudio-education/gradethis")` and the same error appears. Someone told me that the same happened with `dplyr` and Connect and the problem was with a **ñ** and a **á** that weren’t between "".

**Comment by schloerke** [comment]
Last ditch effort...

```r
remotes::install_github("rstudio/packrat")
remotes::install_github("rstudio-education/gradethis")
```
... restart R / RStudio ...

Then deploy like normal.  

If this still doesn't work, can you post your whole tutorial file, so I can track down the error?  Thank you!

**Comment by gadenbuie** [comment]
@andreavargasmontero We hope you were able to resolve this issue, please let us know if not.
