### ISSUE TITLE
how to grade_result a specific object

### ISSUE THREAD

**Issue by VincentGuyader** [rstudio-education/gradethis#96]
Hi, 

thanks for this amaizing package i'm playing with :)

Maybe I'm missing something, but I cant find a way do do someting like this : 

````markdown

create a `score` objet with value 8

```{r b, exercise = TRUE}

```

```{r b-solution}
score <- 8
```

```{r b-hint-1}
score <- 
```


```{r b-check}
grade_result(
  pass_if(~ score == 8, "OK")
)
```
````

any idea how to do this ?

Regards

**Comment by schloerke** [comment]
### Using `grade_code`

````
```{r b-check}
grade_code("OK")
```
````



### Using only `grade_result`
````
```{r b-check}
grade_result(
  pass_if(8, "OK")
)
```
````

````
```{r b-check}
grade_result(
  pass_if(~ identical(.result, 8), "OK")
)
```
````

**Comment by VincentGuyader** [comment]
Thanks a lot,

In this case : 

-  `grade_code` is good, it allow both `score <- 8` and `8 -> score`, but doesnt allow `score <- 4+4`

- `grade_result` will detect `anything <- 8` or `anything <- 5+3` as correct.

Is there a way to test `score == 8` ? beaucause I dont care how the user will calculate the 8, but I want to be sure that there is an object called 'score' containing 8.


bonus question : is there a way to "debug" (with `brower()` or `debugonce()`) the `grade_result` call in place?

regards

**Comment by schloerke** [comment]
> Is there a way to test score == 8 ? beaucause I dont care how the user will calculate the 8, but I want to be sure that there is an object called 'score' containing 8.

See #100 

> bonus question : is there a way to "debug" (with brower() or debugonce()) the grade_result call in place?

You can supply a function to `pass_if` / `fail_if` and have the function return a logical value.

Example: 

```
always_correct <- function(x) {
  str(x)
  browser()
  TRUE
}
```

**Comment by schloerke** [comment]
Bug related to exec environment of the condition function #101

**Comment by schloerke** [comment]
Closing as original question has been answered and other questions have been outsourced
